### ISSUE TITLE
No default response type

### ISSUE THREAD

**Issue by sebsel** [Inklings-io/selfauth#30]
Seems like we have no default response type at this moment. Is there something to default to?

When I send this:
```
POST / HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: selfauth.dev
Connection: close
User-Agent: Paw/3.1.3 (Macintosh; OS X/10.12.6) GCDHTTPRequest
Content-Length: 172

code=[...]
```

I get the following response:
> Notice: Undefined index: HTTP_ACCEPT in /Users/Seb/code/selfauth/index.php on line 170
>
> Notice: Undefined index: HTTP_ACCEPT in /Users/Seb/code/selfauth/index.php on line 173
> **Error: No Accepted Response Types**
> 
> The client accepts neither JSON nor Form encoded responses.

**Comment by Zegnat** [comment]
Definitely a bug because I didn’t read [the Accept specification](https://tools.ietf.org/html/rfc7231#section-5.3.2) carefully. I was working under the assumption that the `Accept` header would be included on all requests, but you made a request without it. In this case, `Accept: */*` should be implied.

For `*/*` (which means form encoding and JSON are equally accepted) we [default to JSON](https://github.com/Inklings-io/selfauth/blob/557ae5337b0381d1082438480da08a4728a8b063/index.php#L178), though I would love it to default form encoding (see #12).
